### ISSUE TITLE
added twice hello world files for python

### ISSUE THREAD

**Issue by adililhan** [aybarscengaver/hello-world#17]
https://github.com/aybarscengaver/hello-world/blob/master/hello-world.py

https://github.com/aybarscengaver/hello-world/blob/master/hello_world.py

**Comment by adililhan** [comment]
Why was this?

**Comment by aybarscengaver** [comment]
@adililhan basic reason in commit message. https://github.com/aybarscengaver/hello-world/commit/63160bbd5d58efc735b19ac98d4dd721a72f355a

**Comment by adililhan** [comment]
```
print ("Hello world!")
```

this code works on python2 and python3 versions, fyi.

**Comment by aybarscengaver** [comment]
you are right. i will remove hello_world.py and update hello-world.py. thank you.
